### ISSUE TITLE
Era 100 Support

### ISSUE THREAD

**Issue by msgrothe** [tkugelberg/Sonos#4]
Hallo Thorsten, die aktuellen Sonos "Era 100" sind noch nicht in der Auswahl vorhanden. 
Wähle ich One oder One SL, funktioniert die grundsätzliche Steuerung, jedoch bei der Gruppierung kommt es zu einem Fehler:
`Fatal error: Uncaught Exception: Error during Soap Call: UPnPError s:Client 501 (ERROR_AV_UPNP_AVT_ACTION_FAILED) in C:\ProgramData\Symcon\modules\.store\de.kugelberg.sonos\libs\sonosAccess.php:812
Stack trace:
#0 C:\ProgramData\Symcon\modules\.store\de.kugelberg.sonos\libs\sonosAccess.php(569): SonosAccess->processSoapCall('/MediaRenderer/...', 'urn:schemas-upn...', 'SetAVTransportU...', Array)
#1 C:\ProgramData\Symcon\modules\.store\de.kugelberg.sonos\SonosPlayer\module.php(1865): SonosAccess->SetAVTransportURI('x-rincon:RINCON...')
#2 C:\ProgramData\Symcon\modules\.store\de.kugelberg.sonos\SonosPlayer\module.php(2641): SonosPlayer->SetGroup(51266)
#3 C:\Windows\System32\-(3): SonosPlayer->RequestAction('MemberOfGroup', 51266)
#4 {main}
  thrown in C:\ProgramData\Symcon\modules\.store\de.kugelberg.sonos\libs\sonosAccess.php on line 812
 in C:\Windows\System32\- on line 1`

Besten Dank vorab für deine Bemühungen.

**Comment by tkugelberg** [comment]
I have added it and submitted it to the beta version of the module.
In addition I will post a new message on https://community.symcon.de/t/sonos-modul/36965/1929 
Please reply with your test results
